version: '2'
services:

  server:
    image: applause/keycloak
    ports:
      - "8080:8080"
    entrypoint: /opt/jboss/docker-entrypoint.sh
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PRIVATE_BIND_ADDRESS: server
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_ROOT_PASSWORD: root_password
